version: "3.8"
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - backend
      - yjswebsocket
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    depends_on:
      - postgres
  yjswebsocket:
    container_name: yjswebsocket
    build:
      context: ./backend
      dockerfile: Dockerfile.ywebsocket
    ports:
      - 1234:1234
    environment:
      - HOST=0.0.0.0
  postgres:
    container_name: postgres
    restart: always
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=blueprint
      - POSTGRES_USER=blueprint
      - POSTGRES_DB=blueprint
    volumes:
      - postgres-volume:/var/lib/postgresql/data
      - ./postgres12/:/docker-entrypoint-initdb.d/
volumes:
  postgres-volume:
